### ISSUE TITLE
mmrlini.v1.json is missing

### ISSUE THREAD

**Issue by RichardBeisser** [DerGoogler/mmrl_install_tools#13]
Hello,
i installed MMRL and MMRL_install_tools using magisk, but installation of modules still doenst work:
![Screenshot_20240324-212119_MMRL](https://github.com/Googlers-Repo/mmrl_install_tools/assets/47367173/6f2b48da-ad93-4a5d-930f-c537335342dc)

What do I have to do?

Thanks

**Comment by raulvasquez** [comment]
You need to "configure" mmrl install tools. Go to the modules page, hit config, change something and change it back. This will generate the file.

**Comment by bphd** [comment]
Same
