### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by webmaster-exit-1** [DerGoogler/mmrl_install_tools#15]
none of the tools are found even after downloading and installing via magisk![Screenshot_2024-05-15-14-20-49-19_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/14a4da9d-6c57-4489-a02c-441e0cab2522)

the picture is when I click install inside mmrl

![Screenshot_2024-05-15-14-22-24-78_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/2d75b500-5865-40dc-83cc-f13279e0b808)

and here's a glimpse at all the errors

I might as well fork this and see if copilot can fix it.

**Comment by DerGoogler** [comment]
Try to edit ModFS

**Comment by webmaster-exit-1** [comment]
> Try to edit ModFS

Could you be more specific? which file, which line, then i'll try to rezip the apk and install

**Comment by DerGoogler** [comment]
> > Try to edit ModFS
> 
> Could you be more specific? which file, which line, then i'll try to rezip the apk and install

![image](https://github.com/DerGoogler/mmrl_install_tools/assets/54764558/6024ecb0-efe0-42ce-9ff3-dadc9eef4e21)

**Comment by DerGoogler** [comment]
@webmaster-exit-1 what do you mean with changing the resolution

**Comment by webmaster-exit-1** [comment]
> @webmaster-exit-1 what do you mean with changing the resolution 

i have to scroll all the way over to read everything in the built in terminal, it is not to the correct resolution. you can clearly see that in my screenshot

**Comment by webmaster-exit-1** [comment]
> @webmaster-exit-1 that is supposed to be.
> I opened an issue above that will implant a feature to enable line wrapping.
> 
> > [!NOTE]
> > Be aware of visual broken install scripts

cool cool. It's not a big deal but if you want this to look professional. line wrapping is a good idea. you could also use an || "or" if the 1st method install script fails it would use the || "or"  method (the edit you suggested i make (which worked))

**Comment by b02860de585071a2** [comment]
I get the exact same error, and I'm actually on a completely fresh system right now.

Magisk 27.0, MMRL 2.15.12, install tools 7.5.12. Everything downloaded clean from GitHub releases, ModFS settings match those shown in this thread. All settings on defaults.

**Comment by DerGoogler** [comment]
@webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

**Comment by webmaster-exit-1** [comment]
> @webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
> https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

alright

**Comment by webmaster-exit-1** [comment]
8.5.12 isn't showing up in mmrl, i can install the zip via magisk but that defeats the purpose ![Screenshot_2024-05-21-11-08-08-76_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/7c307ebd-08b9-4ef7-81d7-cd5a2646c482)

**Comment by webmaster-exit-1** [comment]
Happy to be your helper/tester :)

**Comment by DerGoogler** [comment]
> 8.5.12 isn't showing up in mmrl, i can install the zip via magisk but that defeats the purpose ![Screenshot_2024-05-21-11-08-08-76_fd4950220a21ab37e4313904dcdb5acb.jpg](https://private-user-images.githubusercontent.com/98633966/332534208-7c307ebd-08b9-4ef7-81d7-cd5a2646c482.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTU0OTEsIm5iZiI6MTcxNjMxNTE5MSwicGF0aCI6Ii85ODYzMzk2Ni8zMzI1MzQyMDgtN2MzMDdlYmQtMDhiOS00ZWY3LTgxZDctY2Q1YTI2NDZjNDgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE4MTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NDVkNTQ0MGU5OGM3Njk5Yzk0MTIzZDczNGYxYjdmMGE1ZTE1YTU5YmU4MDU1YTJiYjZjMTM0ZTZmM2NiMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XclViDJrM1WXifx7OD8eqvLiWmibql5rqR8dHaq6_bA)

GMR repo only updates every 6 hours

**Comment by DerGoogler** [comment]
> I'll check back in 6 hrs and post what happened. btw, it's 11am my time

8pm in germany lol

**Comment by b02860de585071a2** [comment]
> @webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
> https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

Just tested it, it *does* work, but with a caveat.

Simply changing `<EXPLORE_INSTALL>` to `<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v8` in ModFS did not work. I had to explicitly use `<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v8**.sh**` (note the file extension). 

I haven't looked through the rest of the source, but I assume somewhere you're using something like `/bin/sh "$EXPLORE_INSTALL"` without specifying the extension, so it's looking to execute a binary named `mmrl_explore_install_v8` instead?

**Comment by b02860de585071a2** [comment]
Also on a seni-related note @DerGoogler , once you choose to install/update a module and enter the terminal (see screenshot) ![Screenshot_20240521-131321_MMRL.png](https://github.com/DerGoogler/mmrl_install_tools/assets/96025485/3916b066-8050-47fd-a6e2-04effb58224a), there is no way to return to MMRL. Using the back button does not do anything, I have to actually force close MMRL and reopen it. 

No idea if this is intended behavior (doesn't seem like it), I can open a new issue if it's a bug :)

**Comment by webmaster-exit-1** [comment]
> > @webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
> > https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12
> 
> Just tested it, it *does* work, but with a caveat.
> 
> Simply changing `<EXPLORE_INSTALL>` to `[…]/mmrl_explore_install_v8` in ModFS did not work. I had to explicitly use `<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v8.sh` (note the file extension). 
> 
> I haven't looked through the rest of the source, but I assume somewhere you're using something like `/bin/sh "$EXPLORE_INSTALL"` or `./$EXPLORE_INSTALL` without specifying the extension, so it's looking to execute a binary named `mmrl_explore_install_v8` instead? 
> 
> 

![Screenshot_2024-05-21-23-54-23-63_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/a32d721c-98f5-435b-aea7-f0dce0533e03)

It finished but with error. weird.

**Comment by webmaster-exit-1** [comment]
oh i never changed modfs back to default. If you want, I can. What was it again?

**Comment by DerGoogler** [comment]
> > > @webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
> > > https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12
> > 
> > 
> > Just tested it, it _does_ work, but with a caveat.
> > Simply changing `<EXPLORE_INSTALL>` to `[…]/mmrl_explore_install_v8` in ModFS did not work. I had to explicitly use `<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v8.sh` (note the file extension).
> > I haven't looked through the rest of the source, but I assume somewhere you're using something like `/bin/sh "$EXPLORE_INSTALL"` or `./$EXPLORE_INSTALL` without specifying the extension, so it's looking to execute a binary named `mmrl_explore_install_v8` instead?
> 
> ![Screenshot_2024-05-21-23-54-23-63_fd4950220a21ab37e4313904dcdb5acb.jpg](https://private-user-images.githubusercontent.com/98633966/332695178-a32d721c-98f5-435b-aea7-f0dce0533e03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDkxNjEsIm5iZiI6MTcxNjQ0ODg2MSwicGF0aCI6Ii85ODYzMzk2Ni8zMzI2OTUxNzgtYTMyZDcyMWMtOThmNS00MzViLWFlYTctZjBkY2UwNTMzZTAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA3MjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjUyNmFkZTE0MTVhNjljYmE1ZmU1YTM5OWE4MDU5OTJlYThhOTRkYmViM2VlMzYyNmMwNmU5ZjkzM2U4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sj4NlH1Vv8Lg23e4d6forX2xIouXbbSCSgrqu3SMec)
> 
> It finished but with error. weird.


this error is normal in the latest build

**Comment by webmaster-exit-1** [comment]
if it is a false positive, it should be hidden from output as to not cause unneeded stress on the end user, since they won't have this knowledge. I suggest running that last part to > 2&1 /dev/null  or something to that affect. Wouldn't you agree?

**Comment by webmaster-exit-1** [comment]
and do not assume, i always hated that when i would work with ppl. I'm not changing anything, env vars. I ran what you asked, the way you asked. I only changed what you asked me to. then I complete the task and report back. If I were to change anything, I would have documented it in my response to you. ;)

**Comment by webmaster-exit-1** [comment]
> > > > @webmaster-exit-1 @b02860de585071a2 could you try the latest release of the install tools? I think, I found the issue
> > > > https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12
> > > 
> > > 
> > > Just tested it, it _does_ work, but with a caveat.
> > > Simply changing `<EXPLORE_INSTALL>` to `[…]/mmrl_explore_install_v8` in ModFS did not work. I had to explicitly use `<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v8.sh` (note the file extension).
> > > I haven't looked through the rest of the source, but I assume somewhere you're using something like `/bin/sh "$EXPLORE_INSTALL"` or `./$EXPLORE_INSTALL` without specifying the extension, so it's looking to execute a binary named `mmrl_explore_install_v8` instead?
> > 
> > ![Screenshot_2024-05-21-23-54-23-63_fd4950220a21ab37e4313904dcdb5acb.jpg](https://private-user-images.githubusercontent.com/98633966/332695178-a32d721c-98f5-435b-aea7-f0dce0533e03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDkxNjEsIm5iZiI6MTcxNjQ0ODg2MSwicGF0aCI6Ii85ODYzMzk2Ni8zMzI2OTUxNzgtYTMyZDcyMWMtOThmNS00MzViLWFlYTctZjBkY2UwNTMzZTAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA3MjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjUyNmFkZTE0MTVhNjljYmE1ZmU1YTM5OWE4MDU5OTJlYThhOTRkYmViM2VlMzYyNmMwNmU5ZjkzM2U4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sj4NlH1Vv8Lg23e4d6forX2xIouXbbSCSgrqu3SMec)
> > 
> > It finished but with error. weird.
> 
> 
> this error is normal in the latest build

![Screenshot_2024-05-23-00-41-45-62_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/68d39a84-7bad-4b22-82ac-7418bc652ba9)

Here's what logcat shows when i open it inside of mmrl.

**Comment by DerGoogler** [comment]
> ![Screenshot_2024-05-23-00-47-23-61_fd4950220a21ab37e4313904dcdb5acb.jpg](https://private-user-images.githubusercontent.com/98633966/333088606-270bef11-7093-4bb6-9fbc-3ac350802249.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE4ODcsIm5iZiI6MTcxNjQ1MTU4NywicGF0aCI6Ii85ODYzMzk2Ni8zMzMwODg2MDYtMjcwYmVmMTEtNzA5My00YmI2LTlmYmMtM2FjMzUwODAyMjQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTE5MThlYjkyOTlkYTg4NTAxYjFkYTU2ODI1MDNkNzM0ZTAzZmVlMzQ2MjZmNDViNDM0MjM5ZWQ3MzA3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rCPSxIQ-w9uY2IUP7UETAjLyrYB9GBvhgY0lyk8jgKM)
> 
> ![Screenshot_2024-05-23-00-47-35-46_fd4950220a21ab37e4313904dcdb5acb.jpg](https://private-user-images.githubusercontent.com/98633966/333088607-3bf24a8e-d768-4c09-a855-394eabbc36a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE4ODcsIm5iZiI6MTcxNjQ1MTU4NywicGF0aCI6Ii85ODYzMzk2Ni8zMzMwODg2MDctM2JmMjRhOGUtZDc2OC00YzA5LWE4NTUtMzk0ZWFiYmMzNmE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NzI0YjlkNDE5OGVmZDY3ZjAwOGRiOTgyNjk5YWRhOTg3YzlkODIwZDlkNTUyZTU1NzMzNjA4YmZkMmQ0ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mRoHpTE-V7z5eI1zy6TSmwEA6_hra5i51S1Q5-tfeig)
> 
> Without modifying modfs. from a clean install. this is what I get.
> 
> Still Broken.
> 
> p.s. I messed something up by trying to install and run `chroot-distro` and had to format my phone. So this is literaly a fresh, new install and error. Just as if I was someone new to flashing the module.
> 
> My Phone: OnePlus Nord N30 5G CPH2513_14.0.0.201(EXT01) (no custom recovery, no custom rom) (magisk root, stock OxygenOS)

You need to edit ModFS when you have the latest install tools version. Check the release notes: https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

**Comment by b02860de585071a2** [comment]
> You need to edit ModFS when you have the latest install tools version. Check the release notes: https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

I somehow missed adding `sh` at the beginning the first time, can confirm it's working for me 100% now.

**Comment by webmaster-exit-1** [comment]
![Screenshot_2024-05-23-00-47-23-61_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/270bef11-7093-4bb6-9fbc-3ac350802249)

![Screenshot_2024-05-23-00-47-35-46_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/3bf24a8e-d768-4c09-a855-394eabbc36a4)

Without modifying modfs. from a clean install. this is what I get.

If the end user has to change it. why not change it in the next release?

**Comment by DerGoogler** [comment]
The next version will have it as default then
