### ISSUE TITLE
I am missing something here

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/mmrl_install_tools#16]
![SmartSelect_20240527_074121_Termux](https://github.com/DerGoogler/mmrl_install_tools/assets/25366502/063e9a29-6032-40c4-906d-e488916416c7)

my config attached.
[mmrl.config.txt](https://github.com/DerGoogler/mmrl_install_tools/files/15455499/mmrl.config.txt)

**Comment by diehard88** [comment]
![Screenshot_20240528_000106_Termux](https://github.com/DerGoogler/mmrl_install_tools/assets/25366502/abd44c14-5c8b-4efd-9e52-5adced7fd1bd)

**Comment by diehard88** [comment]
why do I have two module directories?

<img width="508" alt="image" src="https://github.com/DerGoogler/mmrl_install_tools/assets/25366502/59c43dd5-8f8c-4203-a650-e35015673582">

**Comment by DerGoogler** [comment]
Please migrate to [MMRL-CLI](https://github.com/DerGoogler/MMRL-CLI/releases).
